### ISSUE TITLE
Cannot read properties of null

### ISSUE THREAD

**Issue by lovelord83** [r-o-b-o-t-o/azerothcore-armory#10]
### Current Behaviour

In console, while loading any armory character, a lot of errors are loaded (more than 1k) and loading got a lot of times while loading those errors:

```
viewer.min.js:2 Uncaught TypeError: Cannot read properties of null (reading 'show')
    at ia.updateProgress (viewer.min.js:2:202696)
    at XMLHttpRequest.<anonymous> (viewer.min.js:2:45027)
    at XMLHttpRequest.c (/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1:9405)
viewer.min.js:2 Uncaught TypeError: Cannot read properties of null (reading '1')
    at Kn.setAppearance (viewer.min.js:2:176083)
    at Object.success (viewer.min.js:2:188994)
    at c (jquery-3.6.0.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery-3.6.0.min.js:2:29072)
    at l (jquery-3.6.0.min.js:2:79901)
    at XMLHttpRequest.<anonymous> (jquery-3.6.0.min.js:2:82355)
22viewer.min.js:2 Uncaught TypeError: Cannot read properties of null (reading 'show')
    at ia.updateProgress (viewer.min.js:2:202696)
    at XMLHttpRequest.<anonymous> (viewer.min.js:2:45027)
    at XMLHttpRequest.c (/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1:9405)
viewer.min.js:2 Uncaught TypeError: Cannot read properties of null (reading 'show')
    at ia.updateProgress (viewer.min.js:2:202696)
    at XMLHttpRequest.<anonymous> (viewer.min.js:2:45156)
    at XMLHttpRequest.c (/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1:9405)
644viewer.min.js:2 Uncaught TypeError: Cannot read properties of null (reading 'show')
    at ia.updateProgress (viewer.min.js:2:202696)
    at XMLHttpRequest.<anonymous> (viewer.min.js:2:45027)
    at XMLHttpRequest.c (/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1:9405)
228viewer.min.js:2 Uncaught TypeError: Cannot read properties of null (reading 'show')
    at ia.updateProgress (viewer.min.js:2:202696)
    at XMLHttpRequest.<anonymous> (viewer.min.js:2:45027)
    at XMLHttpRequest.c (rocket-loader.min.js:1:9405)
updateProgress @ viewer.min.js:2
(anonymous) @ viewer.min.js:2
c @ rocket-loader.min.js:1
viewer.min.js:2 Uncaught TypeError: Cannot read properties of null (reading 'forEach')
    at Kn.setAnimation (viewer.min.js:2:178308)
    at Kn.bO (viewer.min.js:2:187586)
    at Kn.bT (viewer.min.js:2:195236)
    at Object.success (viewer.min.js:2:188477)
    at c (jquery-3.6.0.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery-3.6.0.min.js:2:29072)
    at l (jquery-3.6.0.min.js:2:79901)
    at XMLHttpRequest.<anonymous> (viewer.min.js:2:45208)
    at XMLHttpRequest.c (rocket-loader.min.js:1:9405)
```

### Reproduction steps

1- load armory
2- search for a character
3- load a character in armory
4- look in dev console 

### Server operating system

win 11

### Client operating system and browser

win 11 - chrome last version

### Armory revision

*

### AzerothCore revision (commit hash)

*

**Comment by r-o-b-o-t-o** [comment]
This behaviour was ChromieCraft-specific. I had noticed the errors too but didn't really know where they came from, but they were not present on a local install of this repository.
There was a maintenance on the `chromiecraft.com` website today, the errors are gone and the models load way faster now.

**Comment by lovelord83** [comment]
Good to know, that loading is frustrating 😅
