### ISSUE TITLE
Getting error when trying to start

### ISSUE THREAD

**Issue by jagehring** [r-o-b-o-t-o/azerothcore-armory#24]
### Your question

Getting this error when I start it. Any help would be great. Thanks

(node:244923) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
    at PromisePool.query (/var/www/html/azerothcore-armory/node_modules/mysql2/promise.js:341:22)
    at CharacterController.<anonymous> (/var/www/html/azerothcore-armory/src/armory/controllers/CharacterController.ts:150:44)
    at step (/var/www/html/azerothcore-armory/build/armory/controllers/CharacterController.js:44:23)
    at Object.next (/var/www/html/azerothcore-armory/build/armory/controllers/CharacterController.js:25:53)
    at fulfilled (/var/www/html/azerothcore-armory/build/armory/controllers/CharacterController.js:16:58)

**Comment by r-o-b-o-t-o** [comment]
Hi there,
Did you properly fill the `worldDatabase` object in your `config.json` file or the `ACORE_ARMORY_WORLD_DATABASE` values in your environment variables?
Also make sure your database is running and accessible from the host running the armory.

**Comment by jagehring** [comment]
kind of got it working. Now getting this error.

Error on request 5ab7dabe-7bda-4d0c-a635-0ad28a6efc2b. TypeError: Cannot read property 'classId' of undefined
at /var/www/html/azerothcore-armory/src/armory/controllers/CharacterController.ts:388:23
at step (/var/www/html/azerothcore-armory/build/armory/controllers/CharacterController.js:44:23)
at Object.next (/var/www/html/azerothcore-armory/build/armory/controllers/CharacterController.js:25:53)
at step (/var/www/html/azerothcore-armory/build/armory/controllers/CharacterController.js:29:139)
at Object.next (/var/www/html/azerothcore-armory/build/armory/controllers/CharacterController.js:25:53)
at fulfilled (/var/www/html/azerothcore-armory/build/armory/controllers/CharacterController.js:16:58)
at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by r-o-b-o-t-o** [comment]
Do you have custom items on your server, or does it use stock AzerothCore data?

**Comment by jagehring** [comment]
I do have custom items, but I get that error even on toons without custom items.

**Comment by jagehring** [comment]
Going to close since this is an issue with my server. Thanks
